# Generated by Django 4.1.4 on 2023-02-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
